### PR TITLE
alwaysVisible + responsiveness

### PR DESCRIPTION
**Pull request by matthiassnellings**
alwaysVisible parameter was not working. I fixed it.
Every time you hover over the scrollarea the height is recalculated which means the scrollbar becomes responsive.

### CODE REVIEW

**Comment by matthiassnellings** [comment]
that's up to you :)

**Comment by jkuri** [comment]
@matthiassnellings can you rebase it on the top of the master? Then I can merge it.

**Comment by ykushch** [comment]
@jkuri looks good. Also I've created an [enhancement](https://github.com/jkuri/ngSlimscroll/issues/17) ticket for this.

**Comment by jkuri** [comment]
@ykushch thanks. 
@matthiassnellings if you need any help rebasing it please let me know.

**Comment by matthiassnellings** [comment]
I don't know how to rebase.

I just added these two functions:

```
       element.on('mouseenter', function () {
            if (!scope.horizontalScroll) {
                scope.getBarHeight();
            } else {
                scope.getBarWidth();
            }
        });

        element.on('mouseleave', function() {
            if(!scope.alwaysVisible) {
                bar.css({ display: 'none' });
            }
        });
```

and in the init function I added three lines:

```
       scope.init = function () {
            bar.css('top','0');
            if (!scope.horizontalScroll) {
                scope.getBarHeight();
                scope.makeBarDraggable();
            } else {
                scope.getBarWidth();
                scope.makeBarDraggableHorizontal();
            }
            if(!scope.alwaysVisible) {
                bar.css({ display: 'none' });
            }
            scope.attachWheel(el);
            return true;
        }
        scope.init();
    }
```

**Comment by jkuri** [comment]
``` shell
git checkout master
git remote add upstream https://github.com/jkuri/ngSlimscroll.git
git fetch upstream
git rebase upstream/master
git rebase master  // then fix merge conflicts
git push
```

**Comment by matthiassnellings** [comment]
I have to go home now. I'll do it tomorrow

**Comment by jkuri** [comment]
Okay, thanks btw

**Comment by jkuri** [comment]
@matthiassnellings did you managed this? It's not the point that me or @ykushch commit your code.

**Comment by ykushch** [comment]
@matthiassnellings let us know if you need some help with merge. @jkuri and I are ready to help you with that :)

**Comment by jkuri** [comment]
I believe there won't be any response to this. @ykushch if this PR looks good to you can resolve the conflicts and then merge it.

**Comment by ykushch** [comment]
@jkuri @matthiassnellings I've made merge and pushed already :)

**Comment by jkuri** [comment]
@ykushch thanks.

**Pull request merged**
