### PR TITLE
Several performance improvements & code refactoring & gulp task

### PR DESCRIPTION
**Pull request by ykushch**
- Several fixes for performance (it is not all still). 
- Refactor code a bit to be more readable and less error-prone.
- Add `gulp` task for minification.
- Lowered `AngularJS` framework to `1.2.19` in bower file.

### CODE REVIEW

**Comment by jkuri** [comment]
Hi Yuri, thanks for this. If you want I can add you as participant if you would like to maintain this repository further?

**Comment by ykushch** [comment]
Glad you like it. Sure, hope I'll help a bit :)

**Comment by jkuri** [comment]
Ok, you now have push access to this repository. Thanks for helping.

**Comment by ykushch** [comment]
Thanks!

**Pull request merged**
